# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ConfigExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConfigExample
  pod 'FirebaseRemoteConfig', :path => "/Users/paulbeusterien/gh5/firebase-ios-sdk"
  pod 'FirebaseRemoteConfigSwift', :path => "/Users/paulbeusterien/gh5/firebase-ios-sdk"
  pod 'FirebaseSharedSwift', :path => "/Users/paulbeusterien/gh5/firebase-ios-sdk"

  target 'ConfigExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ConfigExampleUITests' do
    # Pods for testing
  end

end
